version: '3.8'
services:
  node-ms:
    image: docker.io/ratipk96/node-ms
    ports:
      - 3000:3000
    environment:
      - MONGO_URL=mongodb://admin:admin@mongodb/?retryWrites=true&w=majority
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    restart: unless-stopped
volumes:
  mongo-data:
    driver: local    